# Basic NumPy Operations Lab

### Part A

In [32]:
import numpy as np

#### Create an array that starts at 1, increasing by 3, with values up to 20

In [33]:
# (start, stop, step), 21 is excluded so only values up to 20 are shown
array = np.arange(1,21,3)  
print(array)

[ 1  4  7 10 13 16 19]


#### Create a new array of shape 3 with random numbers between 0 and 1

In [34]:
# Generate 3 random numbers between 0 and 1, and give the array a shape of (3,)
random_array = np.random.rand(3)
print(random_array)

[0.45862606 0.35692519 0.55371661]


#### Create a 2D array and slice it to get the first two rows and last two rows

In [35]:
# Create the 3x3 array
array_2d = np.array([
            [10, 20, 45],
            [30, 12, 16],
            [42, 17, 56]
            ])

print("Array:\n", array_2d)

# Display the first two rows
first_two_rows = array_2d[:2]
print("\nFirst two rows:\n", first_two_rows)

# Display the last two rows
last_two_rows = array_2d[1:3]
print("\nLast two rows:\n", last_two_rows)

Array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]

First two rows:
 [[10 20 45]
 [30 12 16]]

Last two rows:
 [[30 12 16]
 [42 17 56]]


#### Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays

In [36]:
array_1 = np.array([
                    [1,2],
                    [3,4]
                   ])
array_2 = np.array([
                   [5,6],
                   [7,8]
                   ])

print("Array 1:\n", array_1)
print("\nArray 2:\n", array_2)

# Stack the arrays vertically
vertical_stack = np.vstack((array_1, array_2))
print("\nVertically stacked array:\n", vertical_stack)

# Stack the arrays horizontally
horizontal_stack = np.hstack((array_1, array_2))
print("\nHorizontally stacked array:\n", horizontal_stack)

# Demonstrate horizontal and vertical splitting
split_arrays1 = np.vsplit(vertical_stack, 2)
split_arrays2 = np.hsplit(array_1, 2)
print("\nSplit arrays:\n", split_arrays1, "\n\n", split_arrays2)

Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]

Vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally stacked array:
 [[1 2 5 6]
 [3 4 7 8]]

Split arrays:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])] 

 [array([[1],
       [3]]), array([[2],
       [4]])]


#### Determine if matrix multiplication is possible

In [37]:
# 3x3 matrix
X = np.array([
    [5,7,2],
    [4,5,6],
    [7,4,2]
])

# 3x2 matrix
Y = np.array([
    [4,2],
    [6,2],
    [4,2]
])

print("Matrix X:\n", X)
print("Shape of X: ", X.shape)

print("\nMatrix Y:\n", Y)
print("Shape of Y: ", Y.shape)

# It is possible to multiply these matrixes X @ Y or (3x3) @ (3x2), but it is not possible to multiply them Y @ X or (3x2) @ (3x3)

XY = X @ Y
print("\nMatrix XY:\n", XY)
print("Shape of result: ", XY.shape)

# Demonstrate how YX is not possible

try:
    YX = Y @ X
    print("\nMatrix YX: \n", YX)
except ValueError as error:
    print("\nY*X is not possible")
    print("Reason: ", error)

Matrix X:
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
Shape of X:  (3, 3)

Matrix Y:
 [[4 2]
 [6 2]
 [4 2]]
Shape of Y:  (3, 2)

Matrix XY:
 [[70 28]
 [70 30]
 [60 26]]
Shape of result:  (3, 2)

Y*X is not possible
Reason:  matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


#### Find shape, # of dimensions, and reshape a vector

In [38]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Show x before reshaping
print("Vector x: ", x)
print("Shape of x: ", x.shape)
print("Number of dimensions of x: ", x.ndim)

# Reshape x, then print it alongside its new shape and # of dimensions
xnew = x.reshape(3,1)
print("\nVector xnew:\n", xnew)
print("Shape of xnew: ", xnew.shape)
print("Number of dimensions of xnew: ", xnew.ndim)

# Reshaping y and comparing it before and after being reshaped
ynew = y.reshape(3,1)
print("\nVector y: ", y)
print("Vector ynew:\n", ynew)
print("Shape of ynew: ", ynew.shape)
print("Number of dimensions of ynew: ", ynew.ndim)

Vector x:  [ 2 -1 -8]
Shape of x:  (3,)
Number of dimensions of x:  1

Vector xnew:
 [[ 2]
 [-1]
 [-8]]
Shape of xnew:  (3, 1)
Number of dimensions of xnew:  2

Vector y:  [ 3  1 -2]
Vector ynew:
 [[ 3]
 [ 1]
 [-2]]
Shape of ynew:  (3, 1)
Number of dimensions of ynew:  2


#### Broadcasting
Broadcasting allows NumPy to perform operations between arrays of different compatible shapes. Below are some examples of subtraction and multiplication of a 3x3 matrix

In [39]:
Z  = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Initial matrix:\n", Z)

# Broadcast the subtraction across the entire matrix

Zsub = Z - 2

print("\nSubtracted matrix:\n", Zsub)

# The original matrix is shape (3,3), and the multiplier is shape (3,).
# Broadcasting allows element by element multiplication between the arrays
# the first column is multiplied by 1, the second column by 2, and the third column by 3
mult = np.array([1,2,3])

multiplied = Z * mult
print("\nMultiplied Matrix:\n", multiplied)

Initial matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtracted matrix:
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Multiplied Matrix:
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


### Part B

#### Solve System of Linear Equations

In [40]:
# System 1
A = np.array([
    [2, 3, -4],
    [1, -4, 0]
])

b = np.array([6, 8])

# Print the system of equations with its corresponding matrices
print("Coefficient matrix A:\n", A)
print("\nConstants b:\n", b)

# Find the rank of matrix A
rank_A = np.linalg.matrix_rank(A)

print("\nRank of A:", rank_A)

# Convert A and b into an augmented matrix, and find the rank of it
# When the rank of A and the augmented matrix are equal, but less than the number of unknowns, the system has infinitely many solutions
# In this case, both matrices have a rank of 2, and the number of unknowns is 3 so there are infinitely many solutions
augmented_A = np.column_stack((A, b))

rank_augmented_A = np.linalg.matrix_rank(augmented_A)

print("\nAugmented matrix:\n", augmented_A)
print("\nRank of augmented matrix:", rank_augmented_A)

# Find one possible solution to the system
# This command returns four pieces of info, which is why there are four variables. It finds the solution with the smallest Euclidean norm
solution, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

print("One solution:", solution)

Coefficient matrix A:
 [[ 2  3 -4]
 [ 1 -4  0]]

Constants b:
 [6 8]

Rank of A: 2

Augmented matrix:
 [[ 2  3 -4  6]
 [ 1 -4  0  8]]

Rank of augmented matrix: 2
One solution: [ 1.6692112 -1.5826972 -1.8524173]


In [41]:
# System 2
A2 = np.array([
    [3, -4, 5],
    [-1, 2, -4]
])

b2 = np.array([10, 8])

print("Coefficient matrix A2:\n", A2)
print("\nConstants b2:\n", b2)

rank_A2 = np.linalg.matrix_rank(A2)
print("\nRank of A2: ", rank_A2)

augmented_A2 = np.column_stack((A2, b2))
rank_augmented_A2 = np.linalg.matrix_rank(augmented_A2)

print("\nAugmented matrix A2:\n", augmented_A2)
print("\nRank of augmented matrix: ", rank_augmented_A2)

# This system also has infinitely many solutions due to the principle discussed above
# Find one solution

solution2, residuals2, rank2, singular_values2 = np.linalg.lstsq(A2, b2, rcond=None)

print("\nOne solution:", solution2)

Coefficient matrix A2:
 [[ 3 -4  5]
 [-1  2 -4]]

Constants b2:
 [10  8]

Rank of A2:  2

Augmented matrix A2:
 [[ 3 -4  5 10]
 [-1  2 -4  8]]

Rank of augmented matrix:  2

One solution: [ 7.46067416 -4.62921348 -6.17977528]
